inherit_from:
  - .rubocop_airbnb.yml

Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'spec/*/*'
    - 'app/helpers/application_helper.rb'
